# Variables

@baseUrl = http://localhost:4000

# Health Check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Test Room",
  "description": "This is a test room."
}

###

@roomId = {{getRooms.response.body.$.[0].id}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/88f87671-b1a3-478c-95ad-9b1e21e7c79c/questions
Content-Type: application/json

{
  "question": "O que é Vue js e sua diferença em relação ao Angular?"
}